version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
